config/routes.rb
Muzik::Application.routes.draw do
  resources :artists

  resources :releases

  resources :recordings

  root to: "releases#index"

  devise_for :users
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  #validates_presence_of :name

  has_many :releases, :through => :album_artists
  accepts_nested_attributes_for :releases


  has_many :album_artists, :dependent => :destroy

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @artists = Artist.where("name ilike ?", "%#{params[:q]}%")
    respond_to do |format|
      format.html 
      format.json { render json: @artists.map(&:attributes) }
    end
  end

  def show
    @artist = Artist.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @artist }
    end
  end

  def new
    @artist = Artist.new
    respond_to do |format|
      format.html
      format.json { render json: @artist }
    end
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def create
    @artist = Artist.new(params[:artist])

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render json: @artist, status: :created, location: @artist }
      else
        format.html { render action: "new" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @artist = Artist.find(params[:id])

    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :ok }
    end
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<%= link_to 'New Artist', new_artist_path, :class => "new-link" %>
<table>
<% @artists.each do |artist| %>
  <tr>
    <td><%= artist.name %></td>
    <td><%= link_to 'Show', artist %></td>
    <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
    <td><%= link_to 'Destroy', artist, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table> -->

app/views/artists/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @artist.name %>
</p>


<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>