config/routes.rb
Muzik::Application.routes.draw do
  resources :artists

  resources :releases

  resources :recordings

  root to: "releases#index"

  devise_for :users
end

app/models/recording.rb
class Recording < ActiveRecord::Base
  #validates_presence_of :name

  has_many :releases, :through => :release_tracks
  accepts_nested_attributes_for :releases
  has_many :release_tracks, :dependent => :destroy

  def time
    unless length.nil?
      mm, ss = length.divmod(60)
      if ss < 10
        "%d:0%d" % [mm, ss]
      else
        "%d:%d" % [mm, ss]
      end
    else
      return "--:--"
    end
  end

end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @recordings = Recording.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recordings }
    end
  end

  def show
    @recording = Recording.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recording }
    end
  end

  def new
    @recording = Recording.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recording }
    end
  end

  def edit
    @recording = Recording.find(params[:id])
  end

  def create
    @recording = Recording.new(params[:recording])

    respond_to do |format|
      if @recording.save
        format.html { redirect_to @recording, notice: 'Recording was successfully created.' }
        format.json { render json: @recording, status: :created, location: @recording }
      else
        format.html { render action: "new" }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @recording = Recording.find(params[:id])

    respond_to do |format|
      if @recording.update_attributes(params[:recording])
        format.html { redirect_to @recording, notice: 'Recording was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recording = Recording.find(params[:id])
    @recording.destroy

    respond_to do |format|
      format.html { redirect_to recordings_url }
      format.json { head :ok }
    end
  end
end

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/views/recordings/_form.html.erb
<%= form_for(@recording) do |f| %>
  <% if @recording.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recording.errors.count, "error") %> prohibited this recording from being saved:</h2>

      <ul>
      <% @recording.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :length %><br />
    <%= f.number_field :length %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recordings/edit.html.erb
<h1>Editing recording</h1>

<%= render 'form' %>

<%= link_to 'Show', @recording %> |
<%= link_to 'Back', recordings_path %>

app/views/recordings/index.html.erb
<h1>Listing recordings</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Length</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recordings.each do |recording| %>
  <tr>
    <td><%= recording.name %></td>
    <td><%= recording.length %></td>
    <td><%= link_to 'Show', recording %></td>
    <td><%= link_to 'Edit', edit_recording_path(recording) %></td>
    <td><%= link_to 'Destroy', recording, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recording', new_recording_path %>

app/views/recordings/new.html.erb
<h1>New recording</h1>

<%= render 'form' %>

<%= link_to 'Back', recordings_path %>

app/views/recordings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @recording.name %>
</p>

<p>
  <b>Length:</b>
  <%= @recording.length %>
</p>


<%= link_to 'Edit', edit_recording_path(@recording) %> |
<%= link_to 'Back', recordings_path %>