config/routes.rb
Muzik::Application.routes.draw do
  resources :artists

  resources :releases

  resources :recordings

  root to: "releases#index"

  devise_for :users
end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @releases = Release.includes(:artists).order("release_date desc")
  end

  def show
    @release = Release.find(params[:id])
  end

  def new
    @release = Release.new
    @artist = @release.artists.build
    20.times do
      track = @release.release_tracks.build(:recording => Recording.new)
    end
  end

  def edit
    @release = Release.find(params[:id])
    @release_tracks = @release.release_tracks.order(:track_no)
    (20 - @release_tracks.length).times do
      @release_tracks << @release.release_tracks.build(:recording => Recording.new)
    end
  end

  def create
    @release = Release.new(params[:release])

    respond_to do |format|
      if @release.save
        format.html { redirect_to @release, notice: 'Release was successfully created.' }
        format.json { render json: @release, status: :created, location: @release }
      else
        format.html { render action: "new" }
        format.json { render json: @release.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @release = Release.find(params[:id])

    respond_to do |format|
      if @release.update_attributes(params[:release])
        format.html { redirect_to @release, notice: 'Release was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @release.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @release = Release.find(params[:id])
    @release.destroy

    respond_to do |format|
      format.html { redirect_to releases_url }
      format.json { head :ok }
    end
  end
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/views/releases/_form.html.erb
<%= form_for @release, :html => {:multipart => true} do |f| %>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% if @release.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@release.errors.count, "error") %> prohibited this release from being saved:</h2>

      <ul>
      <% @release.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <span class="find-artist field">
    <%= f.label :artist_tokens, "Artist(s)" %>
    <%= f.text_field :artist_tokens, "data-pre" => @release.artists.map(&:attributes).to_json %>
  </span>
  <span class="release-date field">
    <%= f.label :release_date %><%= f.text_field :release_date, :id => "datepicker" %>
  </span><br>
  
  <% if @release.artists[0].name.blank? %>
  <%= f.fields_for :artists do |artist_form| %>
    <span class="new-artist field">
      <%= artist_form.label :name, "or New Artist" %>
      <%= artist_form.text_field :name %>
    </span><br>
  <% end %>
  <% end %>
  
  <span class="name field">
    <%= f.label :name, "Title" %><%= f.text_field :name %>
  </span><br>
  <span class="genre field">
    <%= f.label :genre %>
    <%= f.select(:genre_id, Genre.order(:name).map{ |g| [g.name, g.id] }, { :include_blank => 'None' }) %>
  </span><br>
  <span class="album-art field">
    <%= f.label :album_art %><%= f.file_field :album_art %>
  </span>
  
  <table id="new-recordings-table">
    <thead>
    <tr>
      <td>No.</td>
      <td>Name</td>
      <td>Length</td>
    </tr>
    </thead>
    <tbody>
  <%= f.fields_for :release_tracks, @release_tracks do |release_track_form| %>
    <tr>
    <td class="new-track-no field">
      <%= release_track_form.text_field :track_no %>
    </td>
  

    <%= release_track_form.fields_for :recording do |recording_form| %>
      <td class="new-recording field">
        <%= recording_form.text_field :name %>
      </td>
      <td class="new-recording-length field">
        <%= recording_form.text_field :length %>
      </td>
    <% end %>
    </tr>
</tbody>
  <% end %>
</table>

<% end %>

app/views/releases/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @release %> |
<%= link_to 'Back', releases_path %>

app/views/releases/index.html.erb
<%= link_to 'New Release', new_release_path, :class => "new-link" %>
<table class="releases">
<% @releases.each do |release| %>
  <tr>
    <td class="artist"><%= release.artists[0].name %></td>
    <td><%= link_to(image_tag(release.album_art_url(:icon).to_s), release) %></td>
    <td><%= release.name %></td>
    <% unless release.release_date.nil? %>
    <td><%= release.release_date.year %></td>
    <td><%= release.release_date.strftime("%b") %></td>
    <td><%= release.release_date.strftime("%e") %></td>
    <% end %>
    <td><%= link_to 'Edit', edit_release_path(release) %></td>
    <td><%= link_to 'Destroy', release, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/releases/new.html.erb
<%= render 'form' %>

app/views/releases/show.html.erb
<p id="notice"><%= notice %></p>
  <div class="show-art <%= genre_css(@release) %>"><%= image_tag @release.album_art_url(:thumb).to_s %></div>
  <h2><%= @release.name %></h2>
  <span>by</span>
  <h3><%= @release.artists[0].name %></h3>

<p>
  <b>Release date:</b>
  <%= @release.release_date.strftime("%A, %B %e, %Y") unless @release.release_date.nil?%>
</p>
<p>
  <strong><%= @release.recordings.length %> tracks</strong> | <%= @release.length_in_text %>
</p>

<table id="show-release-tracks-table">
  <tbody>
    <% for r in @release.release_tracks.order(:track_no) %>
    <tr>
      <td><%= r.track_no %>.</td>
      <td><%= r.recording.name %></td>
      <td><%= r.recording.time %></td>
    </tr>
    <% end %>
  </tbody>
</table>     

<%= link_to 'Edit', edit_release_path(@release) %> |
<%= link_to 'Back', releases_path %>